/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package name.bagi.levente.pedometer;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int speed_units=0x7f050003;
        public static final int speed_value=0x7f050002;
        public static final int step_count=0x7f050000;
        public static final int step_label=0x7f050001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int speed_units=0x7f040003;
        public static final int steps=0x7f040002;
    }
}
